title: "Of Earth â€“ Crina Saad"
theme: minima     # o un altro tema ufficiale GitHub
markdown: kramdown

# Per caricare il CSS personalizzato
plugins:
  - jekyll-include-cache

include:
  - assets/style.css
